### ISSUE TITLE
Can not download https://github.com/kimio-kosaka/webUSB-arduino/archive/v1.0.0.tar.gz

### ISSUE THREAD

**Issue by yokotaccit** [webusb/arduino#94] opened 2022-04-21 07:28 UTC
Hi,
  When I tried https://kimio-kosaka.github.io/webUSB-arduino/package_webUSB_index.json into arduino IDE board manager, I had the error at at the bottom. I also tried to download https://github.com/kimio-kosaka/webUSB-arduino/archive/v1.0.0.tar.gz using chrome and I got this error ::
>The given path has multiple possibilities: #<Git::Ref:0x00007f518371ca38>, #<Git::Ref:0x00007f518371c998>

it seems there are two files with same name. Branch file naming is wrong? I am not sure. Anyway please try board manager and index.json above you can reproduce the problem. Would you please fix?

================= error message ====================
java.lang.RuntimeException: java.lang.Exception: https://github.com/kimio-kosaka/webUSB-arduino/archive/v1.0.0.tar.gz
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:179)
	at java.lang.Thread.run(Thread.java:748)

**Comment by reillyeon** [comment] 2022-04-21 16:45
Closing as a duplicate of kimio-kosaka/webUSB-arduino#2 as the package in question isn't maintained by this project.

**Closed as completed by reillyeon** 2022-04-21 16:45 UTC
